continua el error Console Error
FirebaseError: Firebase Storage: User does not have permission to access 'client_documents/fabianmunozpuello@gmail.com/acceptanceLetter_1748398787194_modelo demanda.docx'. (storage/unauthorized)